-- ─────────────────────────────────────────────────────────────────────────────
-- RLS Policies — DEFERRED
-- ─────────────────────────────────────────────────────────────────────────────
--
-- This migration originally tried to:
--   1. CREATE ROLE app_user / readonly_user
--   2. ALTER ROLE app_user BYPASSRLS
--   3. CREATE POLICY ... TO readonly_user on every org_id table
--
-- All three steps require superuser on the Postgres connection. The app DB is
-- hosted on Supabase, which does NOT grant superuser on the connection Prisma
-- uses. So the migration failed at `ALTER ROLE ... BYPASSRLS` every time it
-- ran, which blocked `prisma migrate deploy` and therefore blocked every
-- Vercel deploy for ~a week — fixes were being committed but never reaching
-- the live site.
--
-- The app does NOT depend on these roles or policies at runtime — Prisma
-- already runs as the DB owner (which bypasses RLS by virtue of ownership)
-- and there is no analytics / readonly user calling the DB today. So the
-- safe move is to neutralize this migration: replace the failing SQL with
-- a no-op SELECT that succeeds on any connection.
--
-- When we genuinely want tenant-isolation hardening, we'll add it as a NEW
-- migration that either:
--   (a) is applied manually via the Supabase dashboard (which grants
--       elevated permissions to admins), or
--   (b) uses Supabase's own RLS / auth helpers instead of trying to create
--       Postgres roles ourselves.
--
-- This migration is intentionally a no-op. Do not extend it.
-- ─────────────────────────────────────────────────────────────────────────────

SELECT 1 WHERE false;
